const $=s=>document.querySelector(s);const state={chapter:1,inventory:[],notes:[],evidence:0,flags:{},bookOrder:[],archiveOrder:[],symbols:[],contract:[],ending:null};
const chapters={1:{label:'CHAPTER 01｜消失之物',scene:'scene-room',caption:'奧里克斯的房間',objective:'調查祖父的房間'},2:{label:'CHAPTER 02｜願望的記錄',scene:'scene-archive',caption:'舊檔案館',objective:'整理三份願望檔案'},3:{label:'CHAPTER 03｜紅色痕跡',scene:'scene-lab',caption:'廢棄研究場所',objective:'重建紅色符號的順序'},4:{label:'CHAPTER 04｜替代品',scene:'scene-shop',caption:'沒有出口的商店',objective:'辨認契約的真正條件'},5:{label:'CHAPTER 05｜緋紅之巔',scene:'scene-void',caption:'願望的空間',objective:'理解並選擇願望的盡頭'}};
function say(text,speaker='尤里',actions=[]){$('#speaker').textContent=speaker;$('#message').textContent=text;$('#dialog-actions').innerHTML=actions.map((a,i)=>`<button class="choice-btn" data-action="${i}">${a.label}</button>`).join('');actions.forEach((a,i)=>$('#dialog-actions').children[i].onclick=a.fn)}
function addNote(text){if(!state.notes.includes(text)){state.notes.push(text);state.evidence++;renderSide()}}
function addItem(name,desc){if(!state.inventory.some(x=>x.name===name)){state.inventory.push({name,desc});renderSide()}}
function showModal(title,body){$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal').classList.remove('hidden')}
function hotspot(label,left,top,fn){return `<button class="hotspot" style="left:${left}%;top:${top}%" data-h="${hotspots.length}">${label}</button>`}
let hotspots=[];function setHotspots(list){hotspots=list;$('#hotspots').innerHTML=list.map((h,i)=>`<button class="hotspot" style="left:${h.x}%;top:${h.y}%">${h.label}</button>`).join('');$('#hotspots').querySelectorAll('button').forEach((b,i)=>b.onclick=hotspots[i].fn)}
function enterChapter(n){state.chapter=n;const c=chapters[n];$('#chapter-label').textContent=c.label;$('#chapter-progress').textContent=`${n} / 5`;$('[id="scene"]').className=`scene ${c.scene}`;$('#scene-caption').textContent=c.caption;$('#objective').textContent=c.objective;renderSide();chapterScene(n)}
function chapterScene(n){if(n===1)chapter1();if(n===2)chapter2();if(n===3)chapter3();if(n===4)chapter4();if(n===5)chapter5()}
function chapter1(){setHotspots([{label:'祖父・奧里克斯',x:14,y:48,fn:()=>{say('「いなくなった……消失了……」他沒有看向你，而是盯著自己的腳踝。','奧里克斯');addNote('祖父反覆說「消失了」，像是在指某種存在，而不只是物品。')}},{label:'腳踝的紅痕',x:28,y:72,fn:()=>{showModal('不完整的圓環','紅色痕跡繞過祖父的腳踝，像一個沒有閉合的圓環。邊緣微微發熱。');addNote('祖父腳踝上的紅痕呈不完整圓環，與房間裡的符號相似。')}},{label:'散落的古書',x:45,y:40,fn:()=>{showModal('書頁上的句子','「先記錄願望，再記錄交換，最後記錄消失。」\n\n這不像目錄，更像是某種排列規則。');addNote('書架紙條：先記錄願望，再記錄交換，最後記錄消失。')}},{label:'書桌',x:73,y:56,fn:()=>{if(state.flags.bookSolved){showModal('隱藏抽屜','舊鑰匙插入鎖孔。抽屜裡只有一本薄薄的研究筆記。\n\n「創造，然後貪求。當一切被吞噬，緋紅之巔將再次出現。」');addItem('祖父的研究筆記','記載願望、交換與紅色眼睛的片段。');addNote('研究筆記：創造，然後貪求；一切被吞噬後，緋紅之巔將再次出現。');say('燈光突然熄滅。黑暗深處，有一隻眼睛正在脈動。','未知的聲音',[{label:'追問「你是誰？」',fn:()=>{say('「你也在尋找消失的東西嗎？」','黑暗');setTimeout(()=>enterChapter(2),700)}},{label:'保持沉默',fn:()=>{say('沉默沒有讓它離開。反而讓那道視線更近了。','尤里');setTimeout(()=>enterChapter(2),700)}}])}else{say('抽屜鎖住了。書桌上刻著和腳踝痕跡相似的圓環。','尤里')}}},{label:'不對齊的書架',x:86,y:25,fn:bookPuzzle}]);say('房間裡瀰漫著灰塵與潮濕的氣味。祖父又在說那句話。');}
function bookPuzzle(){showModal('謎題｜被移動的書',`<p>書架上的五本書被標成符號。請按照紙條「願望 → 交換 → 消失」排列三本核心書。</p><div id="puzzle-options" class="puzzle-options"><button class="choice-btn" data-v="A">A｜張開的眼睛・願望</button><button class="choice-btn" data-v="C">C｜手掌・交換</button><button class="choice-btn" data-v="D">D｜破裂圓環・消失</button></div><p id="puzzle-result"></p>`);let chosen=[];$('#puzzle-options').querySelectorAll('button').forEach(b=>b.onclick=()=>{chosen.push(b.dataset.v);b.disabled=true;b.style.opacity=.5;if(chosen.length===3){if(chosen.join('')==='ACD'){state.flags.bookSolved=true;addItem('舊鑰匙','開啟祖父書桌的隱藏抽屜。');addNote('書架順序 A→C→D：願望、交換、消失。');$('#puzzle-result').textContent='卡榫輕響。書架內部彈出一枚舊鑰匙。';$('#puzzle-result').style.color='#e27b78';}else{$('#puzzle-result').textContent='順序不對。紙條說的是因果，不是書本的年代。';chosen=[];$('#puzzle-options').querySelectorAll('button').forEach(x=>{x.disabled=false;x.style.opacity=1})}}})}
function chapter2(){setHotspots([{label:'借閱紀錄',x:18,y:28,fn:()=>{showModal('借閱紀錄','三份檔案的第一次記錄時間：\nA｜1891 年霜月 03 日\nB｜1887 年雨月 19 日\nC｜1896 年燼月 11 日');addNote('檔案首次記錄時間：B（1887）→A（1891）→C（1896）。')}},{label:'三份願望檔案',x:43,y:38,fn:archivePuzzle},{label:'年代標記',x:78,y:22,fn:()=>showModal('牆上的標記','1887、1891、1896。祖父的字跡寫著：不要按照年齡排列。')}},{label:'鎖住的櫃子',x:78,y:63,fn:()=>{if(state.flags.archiveSolved){addItem('願望紀錄','三個案例：蛋糕、權力、看似什麼都沒有。');say('櫃門打開。最底層的報告寫著：沒有得到任何東西，不代表願望沒有被回應。');setTimeout(()=>enterChapter(3),1000)}else say('鎖上需要三份檔案的時間順序。')}}]);say('檔案館沒有窗戶。灰塵在沒有風的地方緩慢移動。');}
function archivePuzzle(){showModal('謎題｜檔案的正確順序',`<p>依照借閱紀錄的「第一次記錄時間」排列，不要依照檔案中人物的年齡。</p><div id="puzzle-options"><button class="choice-btn" data-v="B">B｜權力與財富</button><button class="choice-btn" data-v="A">A｜鮮奶油蛋糕</button><button class="choice-btn" data-v="C">C｜沒有表面上的獲得</button></div><p id="puzzle-result"></p>`);let chosen=[];$('#puzzle-options').querySelectorAll('button').forEach(b=>b.onclick=()=>{chosen.push(b.dataset.v);b.disabled=true;if(chosen.length===3){if(chosen.join('')==='BACD'.slice(0,3)){state.flags.archiveSolved=true;addNote('檔案時間順序 B→A→C，願望不會因為表面未實現而消失。');$('#puzzle-result').textContent='檔案櫃傳出開鎖聲。';}else{chosen=[];$('#puzzle-result').textContent='順序錯誤：祖父提醒不要按照年齡排列。';$('#puzzle-options').querySelectorAll('button').forEach(x=>x.disabled=false)}}})}
function chapter3(){setHotspots([{label:'入口符號',x:15,y:34,fn:()=>{addNote('研究設施入口的符號代表「召喚」。');say('紅色圓環缺了一角，像有人把某個東西從裡面挖走了。')}},{label:'研究報告',x:40,y:25,fn:()=>{addNote('研究報告：當人們試圖控制它時，願望開始變得不穩定。');showModal('被雨水損壞的報告','「我們以為只要找到它，就能理解它。但它似乎一直在理解我們。」')}},{label:'地下觀察室',x:66,y:53,fn:symbolPuzzle},{label:'舊識別證',x:82,y:76,fn:()=>{addItem('研究識別證','奧里克斯曾參與固定 Crimson Peak 的實驗。');say('照片上的祖父比記憶中年輕。他身後站著三個人，但其中一人的臉被刮掉了。')}}]);say('廢棄設施的電力早已切斷，紅光卻從地下深處一明一滅。');}
function symbolPuzzle(){showModal('謎題｜紅色符號的連結',`<p>將三個符號依照研究中的因果排列：召喚 → 交換 → 消失。</p><div id="puzzle-options"><button class="choice-btn" data-v="召喚">召喚</button><button class="choice-btn" data-v="交換">交換</button><button class="choice-btn" data-v="消失">消失</button></div><p id="puzzle-result"></p>`);let c=[];$('#puzzle-options').querySelectorAll('button').forEach(b=>b.onclick=()=>{c.push(b.dataset.v);b.disabled=true;if(c.length===3){if(c.join('')==='召喚交換消失'){state.flags.symbolSolved=true;addNote('符號順序：召喚→交換→消失。祖父曾試圖固定它的出現。');$('#puzzle-result').textContent='觀察台亮起。錄音開始播放：它一直在理解我們。';setTimeout(()=>enterChapter(4),1100)}else{c=[];$('#puzzle-result').textContent='圓盤退回原位，紅光短暫閃爍。';$('#puzzle-options').querySelectorAll('button').forEach(x=>x.disabled=false)}}})}
function chapter4(){setHotspots([{label:'展示櫃：名字',x:18,y:35,fn:()=>showModal('被遺忘的名字','玻璃裡沒有紙條，只有一個你想不起來的名字。')}},{label:'展示櫃：記憶',x:43,y:35,fn:()=>showModal('模糊的記憶','你看見祖父伸手觸碰紅光，卻不記得自己是否在場。')}},{label:'展示櫃：願望',x:68,y:35,fn:contractPuzzle},{label:'商人',x:83,y:72,fn:()=>{say('有些存在遵守寫下的條件，有些存在只遵守自己理解的願望。','商人',[{label:'拒絕替代交易',fn:()=>{state.flags.refused=true;addNote('你拒絕了商人的替代交易，選擇保留未被改寫的記憶。');say('「那就帶著空白回去吧。」���店的門消失了。','商人');setTimeout(()=>enterChapter(5),1000)}},{label:'接受部分交易',fn:()=>{state.flags.traded=true;addItem('不完整契約','交易者提供具體事物，但不保證你理解結果。');say('「記住，沒有說出口的願望不能成為條件。」','商人');setTimeout(()=>enterChapter(5),1000)}}])}}]);say('商店沒有出口。貨架上的物品像是從別人的夢裡取出來的。');}
function contractPuzzle(){showModal('謎題｜不完整的契約',`<p>把真正寫明的條件與模糊承諾分開。最重要的規則：交換物必須被明確說出。</p><div id="puzzle-options"><button class="choice-btn" data-v="wrong">「我會讓你幸福」是完整條件</button><button class="choice-btn" data-v="right">「你交出一段記憶，我交付一個名字」是完整條件</button></div><p id="puzzle-result"></p>`);$('#puzzle-options').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.dataset.v==='right'){state.flags.contractSolved=true;addNote('商人的契約揭示：明確說出的交換才成立，模糊承諾不等於結果。');$('#puzzle-result').textContent='契約上的紅墨水褪去，露出真正條件。'}else $('#puzzle-result').textContent='這只是承諾，不是明確寫出的交換物。'})}
function chapter5(){setHotspots([{label:'反覆出現的書架',x:17,y:28,fn:()=>showModal('書架','第一章的三本書重新出現。願望、交換、消失。它們沒有被摧毀，只是換了位置。')}},{label:'沒有倒影的鏡子',x:42,y:25,fn:()=>{addNote('鏡子沒有倒影：Crimson Peak 可能不是一個能被定位的地方。');say('鏡中沒有你，只有一隻慢慢睜開的眼睛。')}},{label:'研究桌',x:72,y:33,fn:finalWishPuzzle},{label:'深紅色眼睛',x:51,y:65,fn:cyclePuzzle}]);say('房間回到原處，又不像原來。門通往同一扇門，窗外沒有天空。');}
function finalWishPuzzle(){showModal('最終推理｜真正的願望',`<p>根據你收集的證據，祖父真正追求的是什麼？選擇最符合他的行動。</p><div id="puzzle-options"><button class="choice-btn" data-v="locate">找到 Crimson Peak 的位置</button><button class="choice-btn" data-v="memory">恢復失去的記憶</button><button class="choice-btn" data-v="control">讓所有願望都能被控制</button><button class="choice-btn" data-v="understand">理解 Crimson Peak 為何出現</button></div><p id="puzzle-result"></p>`);$('#puzzle-options').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.flags.wish=b.dataset.v;addNote('你的推理：祖父的願望指向「'+b.textContent+'」。');$('#puzzle-result').textContent='記憶中的聲音回答：你終於說出了它。';setTimeout(()=>{$('#modal').classList.add('hidden')},700)})}
function cyclePuzzle(){showModal('最終謎題｜緋紅之巔的循環',`<p>把循環理解為：創造 → 貪求 → 消失 → 再現。消失不是終點。</p><div id="puzzle-options"><button class="choice-btn" data-v="wrong">創造 → 消失 → 貪求 → 再現</button><button class="choice-btn" data-v="right">創造 → 貪求 → 消失 → 再現</button></div><p id="puzzle-result"></p>`);$('#puzzle-options').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.dataset.v==='right'){state.flags.cycle=true;$('#puzzle-result').textContent='四個圓環彼此咬合。最後的選擇已經醒來。';setTimeout(showEndingChoices,700)}else $('#puzzle-result').textContent='研究筆記中的「創造，然後貪求」否定了這個順序。'})}
function showEndingChoices(){showModal('最後的選擇','Crimson Peak 沒有問你要什麼。它只等待你決定要如何對待這個循環。<div class="dialog-actions"><button class="choice-btn" id="end-cut">切斷交換</button><button class="choice-btn" id="end-continue">讓交換繼續</button><button class="choice-btn" id="end-understand">承認無法完全理解</button></div>');$('#end-cut').onclick=()=>end('cut');$('#end-continue').onclick=()=>end('continue');$('#end-understand').onclick=()=>end('understand')}
function end(type){state.ending=type;$('#modal').classList.add('hidden');$('#game-screen').classList.add('hidden');$('#ending-screen').classList.remove('hidden');const data={cut:['ENDING A｜切斷交換','你燒掉召喚記錄。眼睛閉合了，但紅痕沒有消失。交換暫時中斷；在更遠的地方，某個願望仍然正在形成。'],continue:['ENDING B｜願望仍在繼續','你把研究重新放回書架。城市的角落逐一亮起深紅色的眼睛，而新的願望記錄出現在你的筆記本上。'],understand:['ENDING C｜緋紅之巔並不在遠方','你沒有摧毀它，也沒有向它許願。你承認它無法被人類的善惡或控制定義。眼睛最後問：「你終於停止尋找答案了嗎？」']}[type];$('#ending-title').textContent=data[0];$('#ending-text').textContent=data[1];$('#ending-summary').textContent=`你發現了 ${state.evidence} 條線索，${state.inventory.length} 件道具。`}
function renderSide(){const ip=$('#inventory-panel');ip.innerHTML=state.inventory.length?state.inventory.map(x=>`<div class="item"><button><span class="item-name">${x.name}</span><span class="item-desc">${x.desc}</span></button></div>`).join(''):'<p class="item-desc">尚未取得道具。點擊場景中的物件開始調查。</p>';$('#notes-panel').innerHTML=state.notes.length?state.notes.map(x=>`<div class="note">${x}</div>`).join(''):'<p class="item-desc">重要發現會記錄在這裡。</p>';$('#evidence-count').textContent=state.evidence}
function start(){state.chapter=1;state.inventory=[];state.notes=[];state.evidence=0;state.flags={};$('#title-screen').classList.add('hidden');$('#game-screen').classList.remove('hidden');enterChapter(1)}
$('#start-game').onclick=start;$('#ending-restart').onclick=()=>{$('#ending-screen').classList.add('hidden');$('#title-screen').classList.remove('hidden')};$('#restart-game').onclick=()=>{if(confirm('要重新開始調查嗎？'))start()};$('#close-modal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#inventory-panel').classList.toggle('hidden',t.dataset.tab!=='inventory');$('#notes-panel').classList.toggle('hidden',t.dataset.tab!=='notes')});renderSide();
